/**
 * "Live tonight. Nothing to buy." — the setup strip (Milestone 40).
 *
 * WHY THIS SECTION EXISTS. The single biggest reason an SMB owner doesn't start a
 * trial is the suspicion that setting it up will be a project. Until M30 that
 * suspicion was CORRECT — ScoreFlow was NFC-only, so "try it" meant buying chips and
 * programming them. M30 killed that with the printable QR kit, and the landing page
 * never said so. (Worse: the scroll story literally said "no QR to squint at".)
 *
 * So this strip does one job: show, in three pictures, that there is nothing to buy
 * and nothing to install. Print → put one on each table → you're live.
 *
 * ⚠️ THE QR CODE IS REAL. It is generated by the same `qrMatrix()` the print kit uses
 * and it genuinely resolves (to /signup — see `page.tsx`, which encodes it). A
 * decorative fake would be both a lie and trivially detectable by anyone who points a
 * camera at it, which is the last thing a page whose whole pitch is "we're the honest
 * tool" can afford. The note under the strip says plainly where it goes.
 *
 * SERVER component: the matrix arrives as a prop (plain booleans, so it crosses the
 * RSC boundary fine) and nothing here is interactive.
 */

import type { QrMatrix } from "@/lib/qr";
import QrCode from "../QrCode";
import Reveal from "../Reveal";
import { CONTAINER, SECTION } from "./tokens";

/** The step number — a small dark pill, in place of an arrow or an icon. */
function StepNumber({ n }: { n: number }) {
  return (
    <span className="flex h-6 w-6 flex-none items-center justify-center rounded-full bg-[#1D1D1F] text-[12px] font-semibold text-white">
      {n}
    </span>
  );
}

/**
 * One panel: a grey tile with the visual floating in it, then the step and one line.
 *
 * The tile is what makes a WHITE mock (paper card, email) read as an object on a
 * white page — without it the cards would dissolve into the background.
 */
function Panel({
  n,
  title,
  children,
  visual,
}: {
  n: number;
  title: string;
  children: React.ReactNode;
  visual: React.ReactNode;
}) {
  return (
    // `h-full` keeps all three panels the SAME height regardless of how many lines of
    // copy each carries — the grid row stretches to the tallest and every panel fills
    // it, so their grey cards line up top and bottom.
    <div className="flex h-full flex-col rounded-3xl bg-[#F5F5F7] p-6">
      {/* Fixed height so the three visuals sit on a common baseline. Sized by the
          tallest of them — the specimen card, whose QR is deliberately big enough to
          actually scan off a screen (see TableCard). */}
      <div className="flex h-[224px] items-center justify-center">{visual}</div>

      {/* ⚠️ MOBILE ALIGNMENT: on a phone each panel is full-width, and the visual
          above is centred — so left-aligning the title + copy made every card mix
          centre and left, which reads as untidy (and clashed with the NFC band below,
          which is centred on mobile). So the text is CENTRED on mobile and restored to
          LEFT at `sm:` — the desktop three-column layout is unchanged. */}
      <div className="mt-6 flex items-center justify-center gap-2.5 sm:justify-start">
        <StepNumber n={n} />
        <h3 className="text-[16px] font-semibold tracking-[-0.01em] text-[#1D1D1F]">
          {title}
        </h3>
      </div>
      <p className="mt-1.5 text-center text-[14px] leading-relaxed text-[#6E6E73] sm:text-left">
        {children}
      </p>
    </div>
  );
}

/** The brand mark on a table card — the first initial, exactly like the real kit. */
function BrandDisc() {
  return (
    <span className="mx-auto flex h-5 w-5 items-center justify-center rounded-full bg-amber-500 text-[9px] font-semibold text-white">
      F
    </span>
  );
}

/**
 * Visual 1 — a specimen of the card the print kit produces.
 *
 * ⚠️ THE QR IS SIZED TO BE SCANNED, not just to look like a QR. We tell the reader
 * "scan it", so it has to be genuinely pleasant to scan off a screen: at 112px the
 * 29-module code gives ~3.8px per module (≈3cm wide on a typical display), which a
 * phone camera reads instantly. The first draft drew it at 78px — decodable in a
 * lab, fiddly in real life, which is the worst of both worlds when you've just
 * invited someone to try it.
 */
function TableCard({ qr }: { qr: QrMatrix }) {
  return (
    <div className="w-[160px] rounded-xl border border-dashed border-[#C7C7CC] bg-white p-3 text-center shadow-[0_8px_24px_-12px_rgba(0,0,0,0.25)]">
      <BrandDisc />
      <p className="mt-1.5 text-[9px] font-semibold text-[#1D1D1F]">
        Scan to rate your meal
      </p>
      <QrCode
        matrix={qr}
        className="mx-auto mt-1.5 w-[112px]"
        title="Scan to open ScoreFlow"
      />
      <p className="mt-1.5 text-[10px] font-semibold text-[#1D1D1F]">Table 7</p>
      <p className="mt-0.5 text-[8px] text-[#AEAEB2]">Ten seconds · no app</p>
    </div>
  );
}

/** A thumbnail of the same card — used to show a stack of them, one per table. */
function MiniCard({ qr, label }: { qr: QrMatrix; label: string }) {
  return (
    <div className="w-[74px] rounded-lg border border-[#E5E5EA] bg-white p-2 text-center shadow-[0_8px_20px_-10px_rgba(0,0,0,0.3)]">
      <QrCode
        matrix={qr}
        className="mx-auto w-[44px]"
        title={`${label} card`}
      />
      <p className="mt-1 text-[7px] font-semibold text-[#1D1D1F]">{label}</p>
    </div>
  );
}

/**
 * Visual 2 — one card per table, fanned out.
 *
 * ⚠️ The horizontal step (58px) is set against the card width (74px), not chosen for
 * looks: a 46px step overlapped by 28px and the NEXT card landed on top of "Table 2",
 * burying the very label that makes the point ("each card is for one table"). At 58px
 * the overlap is 16px — enough to read as a stack, not enough to eat a label.
 */
function CardStack({ qr }: { qr: QrMatrix }) {
  return (
    <div className="relative h-[132px] w-[190px]">
      <div className="absolute left-0 top-6 -rotate-6">
        <MiniCard qr={qr} label="Table 1" />
      </div>
      <div className="absolute left-[58px] top-1 rotate-1">
        <MiniCard qr={qr} label="Table 2" />
      </div>
      <div className="absolute left-[116px] top-7 rotate-6">
        <MiniCard qr={qr} label="Table 3" />
      </div>
    </div>
  );
}

/** Visual 3 — the alert that proves it's working, minutes later. */
function AlertCard() {
  return (
    <div className="w-[176px] rounded-xl border border-[#E5E5EA] bg-white p-3 shadow-[0_8px_24px_-12px_rgba(0,0,0,0.25)]">
      <div className="flex items-center gap-2">
        <span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#1D1D1F] text-[9px] font-semibold text-white">
          S
        </span>
        <div className="min-w-0 flex-1">
          <p className="truncate text-[10px] font-semibold text-[#1D1D1F]">
            ScoreFlow
          </p>
          <p className="text-[8px] text-[#AEAEB2]">now</p>
        </div>
      </div>

      <p className="mt-2 text-[10px] font-semibold leading-snug text-[#1D1D1F]">
        Fucco: an unhappy diner (3/10)
      </p>

      <div className="mt-1.5 rounded-lg bg-[#F2F2F7] p-1.5">
        <p className="text-[9px] font-semibold text-[#1D1D1F]">
          3/10 — order 1042, table 7
        </p>
        <p className="mt-0.5 text-[8px] text-[#6E6E73]">Tagged: Food was cold</p>
      </div>

      <div className="mt-2 rounded-lg bg-amber-500 py-1.5 text-center text-[9px] font-semibold text-white">
        Open dashboard
      </div>
    </div>
  );
}

/**
 * The universal "contactless / tap" symbol — three radiating arcs. It's the mark
 * everyone already knows from tapping a card to pay, so it reads as "tap here"
 * instantly, without a label.
 */
function TapWaves({ className = "" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 32 32"
      fill="none"
      stroke="currentColor"
      strokeWidth={2.6}
      strokeLinecap="round"
      className={className}
      aria-hidden="true"
    >
      <path d="M11 9a11 11 0 0 1 0 14" />
      <path d="M16 6a16 16 0 0 1 0 20" />
      <path d="M21 3.5a21 21 0 0 1 0 25" />
    </svg>
  );
}

/**
 * The NFC visual — a phone tapping the reusable chip on the table.
 *
 * ⚠️ WHY THIS EXISTS. NFC is a first-class way to use ScoreFlow (it predates QR on
 * this product), but the page gave QR a rich specimen card and NFC only a passing
 * line of text. That's an unfair picture: a reader skims the visuals, so a feature
 * with no visual reads as an afterthought. This gives NFC its own image, drawn in the
 * same near-black + one-amber-accent language as everything else.
 *
 * It's an illustration, not a QR: nothing here is scannable, so it carries no
 * "this is real" claim — it just shows the gesture (tap phone → chip).
 */
function NfcTap() {
  return (
    <div className="relative flex h-[132px] w-[184px] items-center justify-center">
      {/* The reusable NFC chip sitting on the table. */}
      <div className="absolute bottom-3 left-4 flex h-20 w-20 items-center justify-center rounded-full border border-[#E5E5EA] bg-white shadow-[0_8px_24px_-12px_rgba(0,0,0,0.28)]">
        <span className="flex h-11 w-11 items-center justify-center rounded-full bg-amber-500 text-white">
          <TapWaves className="h-6 w-6" />
        </span>
      </div>

      {/* The phone, tilted toward the chip as if being tapped to it. */}
      <div className="absolute right-4 top-1 h-24 w-[54px] rotate-[16deg] rounded-[15px] bg-[#1D1D1F] p-[3px] shadow-[0_14px_34px_-12px_rgba(0,0,0,0.55)]">
        <div className="flex h-full w-full items-start justify-center rounded-xl bg-gradient-to-b from-[#3A3A3C] to-[#1D1D1F] pt-2">
          <span className="h-1 w-4 rounded-full bg-white/25" />
        </div>
      </div>
    </div>
  );
}

export default function SetupStrip({ qr }: { qr: QrMatrix }) {
  return (
    <section className={SECTION}>
      <div className={CONTAINER}>
        <Reveal>
          <div className="max-w-2xl">
            <p className="text-[14px] font-medium text-[#6E6E73]">Setting up</p>
            <h2 className="mt-4 text-[30px] font-semibold leading-[1.1] tracking-[-0.02em] text-[#1D1D1F] sm:text-[44px]">
              Live tonight. Nothing to buy.
            </h2>
            <p className="mt-5 text-[17px] leading-relaxed text-[#6E6E73]">
              Print the kit, stand a card on each table, and you&apos;re taking
              feedback by tonight&apos;s service. No chips, no app, no hardware.
            </p>
          </div>
        </Reveal>

        {/* One column on a phone — the three panels simply stack, and the numbered
            pills keep the sequence readable without arrows. */}
        <div className="mt-14 grid gap-5 sm:grid-cols-3 sm:gap-6">
          <Reveal>
            <Panel n={1} title="Print the kit" visual={<TableCard qr={qr} />}>
              One card per table, generated for you. A printer is the only equipment
              you need.
            </Panel>
          </Reveal>

          <Reveal delay={90}>
            <Panel n={2} title="Put one on each table" visual={<CardStack qr={qr} />}>
              Each card carries its own table&apos;s link, so every score arrives
              knowing where it came from.
            </Panel>
          </Reveal>

          <Reveal delay={180}>
            <Panel n={3} title="That&rsquo;s it — you&rsquo;re live" visual={<AlertCard />}>
              The first unhappy guest reaches your inbox in seconds — while
              they&apos;re still at the table, still holding the bill.
            </Panel>
          </Reveal>
        </div>

        {/* The NFC alternative, with its own visual so it's a real option, not a
            footnote. Framed as the "or" to the QR story above — QR owns "nothing to
            buy"; NFC is the tap-instead-of-scan upgrade. */}
        <Reveal delay={240}>
          <div className="mt-6 flex flex-col items-center gap-6 rounded-3xl border border-[#E5E5EA] bg-white p-6 text-center sm:flex-row sm:gap-9 sm:p-8 sm:text-left">
            <div className="flex-none">
              <NfcTap />
            </div>
            <div>
              <p className="text-[13px] font-medium text-[#AEAEB2]">
                Or, if you&apos;d rather tap
              </p>
              <h3 className="mt-1.5 text-[20px] font-semibold tracking-[-0.01em] text-[#1D1D1F] sm:text-[22px]">
                No camera? Tap instead.
              </h3>
              <p className="mt-2 max-w-md text-[15px] leading-relaxed text-[#6E6E73]">
                Load the same link onto a reusable NFC chip and guests just tap their
                phone to the table — no camera, no app. Buy the chips once; they last
                for years.
              </p>
            </div>
          </div>
        </Reveal>

        {/* Honesty note. The QR above is genuinely scannable, so it has to say where
            it goes — a "specimen" card whose QR quietly did nothing (or went somewhere
            unexpected) would be exactly the kind of small lie this page can't afford. */}
        <Reveal delay={300}>
          <p className="mt-8 text-[13px] text-[#AEAEB2]">
            The QR code above is real — scan it and ScoreFlow opens on your phone. The
            cards you print carry your own restaurant&apos;s link instead.
          </p>
        </Reveal>
      </div>
    </section>
  );
}
